### ISSUE TITLE
Land surface scheme

### ISSUE THREAD

**Issue by dmey** [samhatfield/speedy_physics.f90#2]
I noticed that this repository does not contain all parametrization files used in SPEEDY. Any chance you could add files for the land surface parametrization scheme?

**Comment by samhatfield** [comment]
Hi @dmey - thanks for your interest in the repository.

Are you referring to [this land model](https://github.com/samhatfield/speedy.f90/blob/master/source/land_model.f90)?

This repository has an unusual history. The routines here are modernised versions (or yet-to-be modernised versions) of the physics routines in SPEEDY (F77 version). They were released separately by the developers under a permissive license on the [SPEEDY website](http://users.ictp.it/~kucharsk/speedy-net.html) (scroll down to "SPEEDY physical parameterization package") and you can see them in the [first commit](https://github.com/samhatfield/speedy_physics.f90/tree/4e352347f907eafa255f7b050947fd81f6bd253c).

I cannot import anything else into this repository, including anything related to the land surface, because only the routines in the above package are covered by the [license](https://github.com/samhatfield/speedy_physics.f90/blob/main/licence.txt).

You might be wondering why I can't just copy them across from speedy.f90. That repository actually has a different license, negotiated with the SPEEDY developers, and one less permissive. If I brought the land surface model into this repository, I would have to downgrade the license, and this wouldn't be acceptable for some of the users of this repository (specifically the "non-commercial purposes" condition in speedy.f90's license).

So a bit annoying, but I'm afraid it's not possible :(

**Comment by dmey** [comment]
Thanks @samhatfield. Indeed, I was referring to https://github.com/samhatfield/speedy.f90/blob/master/source/land_model.f90. I understand the history and the lic issue so no problem, I was just surprised to see that the land model was not released with the other parametrizations, would you know why it was so?

**Comment by samhatfield** [comment]
I suspect it's simply because it's treated differently from the other physics schemes. The only files in the separate package above are basically the ones with a phy_ prefix - these are called inside the dynamical core, unlike the land surface model.

One solution for you, assuming you're okay with using a relatively restrictive license, is to fork this repo and use the license for speedy.f90. Then you'd be welcome to put any of the remaining speedy.f90 code into that repo.

**Comment by dmey** [comment]
Thanks and needed MIT but no problem, thanks for letting me know! Feel free to close this now.
